import {
  LayoutDashboard,
  BarChart3,
  Settings,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Menu,
  Check,
  CheckCircle,
  CheckCircle2,
  X,
  XCircle,
  TriangleAlert,
  AlertTriangle,
  ShieldCheck,
  Shield,
  ShieldAlert,
  ShieldHalf,
  Lock,
  Key,
  KeyRound,
  FileKey,
  Server,
  Cpu,
  Database,
  Layers,
  GitMerge,
  Globe,
  Globe2,
  Wifi,
  ShoppingCart,
  CreditCard,
  Package,
  Users,
  Building2,
  Landmark,
  Handshake,
  BookOpen,
  FileText,
  Code,
  Code2,
  HelpCircle,
  LifeBuoy,
  MessageCircle,
  Phone,
  Mail,
  Video,
  Tag,
  ExternalLink,
  Search,
  Clock,
  Clock3,
  RefreshCw,
  Loader2,
  Star,
  Sparkles,
  BadgeCheck,
  Award,
  Flame,
  Activity,
  Trophy,
  Brush,
  Rocket,
  Box,
  Boxes,
  Linkedin,
  Twitter,
  Youtube,
  MapPin,
  Headphones,
  LogOut,
  Bell,
  Loader,
  Pause,
  Play,
  MailCheck,
  ShoppingBag,
  MessageSquare,
  User,
  Receipt,
  TrendingUp,
  TrendingDown,
  ShieldX,
  AlertCircle,
  LayoutTemplate,
  Microscope,
  Crown,
  Trash2,
  Scan,
  Bug,
  Eye,
  EyeOff,
  Target,
  Radar,
  Bot,
  Wand2,
  Zap,
  Link,
  SlidersHorizontal,
  Hash,
  FileCode2,
  ClipboardCopy,
  Info,
  Terminal,
  Monitor,
  Download,
  Wrench,
  HardDrive,
  Cloud,
  RotateCw,
  Brain,
  Ban,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";
export type IconType = keyof typeof ICONS;
export const ICONS: Record<string, LucideIcon> = {
  bot : Bot,
  link:Link,
  mfa: ShieldCheck,
  adaptive: Brain,
  integration: Link,
  cloud: Cloud,
  passwordless: Ban,
  scale: TrendingUp,
  wand2 : Wand2,
  zap : Zap,
  triangleAlert : TriangleAlert,
  trendingDown : TrendingDown,
  shieldX : ShieldX,
  eye:Eye,
  eyeOff : EyeOff,
  crown : Crown,
  trash2 : Trash2,
  scan : Scan,
  bug : Bug,
  target : Target,
  radar : Radar,
  dashboard: LayoutDashboard,
  alertCircle : AlertCircle,
  layoutTemplate: LayoutTemplate,
  microscope : Microscope,
  messageSquare : MessageSquare,
  user : User,
  receipt : Receipt,
  chart: BarChart3,
  settings: Settings,
  logout: LogOut,
  pause: Pause,
  play: Play,
  loader: Loader2,
  mailCheck : MailCheck,
  creditCard:CreditCard,
  slidersHorizontal: SlidersHorizontal,
  menu: Menu,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  checkCircle: CheckCircle,
  success: CheckCircle2,
  close: X,
  xCircle: XCircle,
  alert: AlertTriangle,
  shield: Shield,
  shieldCheck : ShieldCheck,
  shieldRaw: Shield,
  shieldAlert: ShieldAlert,
  shieldHalf: ShieldHalf,
  lock: Lock,
  key: Key,
  keyRound: KeyRound,
  fileKey: FileKey,
  server: Server,
  cpu: Cpu,
  database: Database,
  layers: Layers,
  gitMerge: GitMerge,
  trending: TrendingUp,
  globe: Globe,
  globe2: Globe2,
  wifi: Wifi,
  cart: ShoppingCart,
  box: Box,
  bag:ShoppingBag,
  package: Package,
  users: Users,
  building: Building2,
  landmark: Landmark,
  handshake: Handshake,
  book: BookOpen,
  bookOpen: BookOpen,
  file: FileText,
  code: Code,
  code2: Code2,
  bell:Bell,
  help: HelpCircle,
  support: LifeBuoy,
  lifeBuoy: LifeBuoy,
  message: MessageCircle,
  phone: Phone,
  mail: Mail,
  video: Video,
  tag: Tag,
  externalLink: ExternalLink,
  search: Search,
  clock: Clock,
  clockAlt: Clock3,
  refresh: RefreshCw,
  star: Star,
  sparkles: Sparkles,
  badge: BadgeCheck,
  award: Award,
  flame: Flame,
  activity: Activity,
  trophy: Trophy,
  brush: Brush,
  rocket: Rocket,
  boxes: Boxes,
  linkedin: Linkedin,
  twitter: Twitter,
  youtube: Youtube,
  mapPin: MapPin,
  headphones: Headphones,
  hash: Hash,
  fileCode: FileCode2,
  clipboardCopy: ClipboardCopy,
  info: Info,
  terminal: Terminal,
  tenant: Building2,
  report: BarChart3,
  monitor: Monitor,
  download: Download,
  wrench: Wrench,
  hardDrive: HardDrive,
  rotateCw: RotateCw,
  protection: Shield,
  encryption: Lock,
  files: Package,
  disclaimer: FileText,
  discovery: Search,
  visibility: BarChart3,
  automation: Settings,
  governance: Landmark,
};