export const dvProducts = [

  // ─────────────────────────────────────────────
  // DV — Standard (Single Domain)
  // ─────────────────────────────────────────────

  {
    name: "Sectigo DV",
    slug: "sectigo-dv",
    category: "SSL",
    validation: "DV",
    productType: "Standard",
    tier: "Basic",
    brand: "Sectigo",
    description: "Sectigo DV, kişisel siteler ve bloglar için uygun fiyatlı giriş seviyesi domain doğrulamalı SSL sertifikasıdır.",
    shortDescription: "Hızlı ve ekonomik giriş seviyesi DV SSL.",
    price: { oneYear: 299, twoYear: 549, threeYear: 799 },
    specs: { Warranty: "$10,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Domain doğrulaması (5–10 dk)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Tüm modern tarayıcılarla uyumluluk",
      "Sınırsız sunucu lisansı",
      "30 gün para iade garantisi",
    ],
    rating: 4.5, reviewCount: 210, featured: false, inStock: true,
  },

  {
    name: "Thawte SSL 123 DV",
    slug: "thawte-ssl123-dv",
    category: "SSL",
    validation: "DV",
    productType: "Standard",
    tier: "Basic",
    brand: "Thawte",
    description: "Thawte SSL 123, basit kurulum ve hızlı domain doğrulaması sunan güvenilir DV SSL sertifikasıdır.",
    shortDescription: "Güvenilir ve hızlı DV SSL.",
    price: { oneYear: 599, twoYear: 1099, threeYear: 1499 },
    specs: { Warranty: "$100,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Domain doğrulaması (5–10 dk)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Tüm modern tarayıcılarla uyumluluk",
      "7/24 teknik destek",
      "30 gün para iade garantisi",
    ],
    rating: 4.6, reviewCount: 140, featured: false, inStock: true,
  },

  {
    name: "PositiveSSL DV",
    slug: "positivessl-dv",
    category: "SSL",
    validation: "DV",
    productType: "Standard",
    tier: "Basic",
    brand: "PositiveSSL",
    description: "PositiveSSL, bütçe dostu fiyatıyla kişisel siteler ve küçük projeler için idealdir.",
    shortDescription: "En uygun fiyatlı DV SSL çözümü.",
    price: { oneYear: 149, twoYear: 279, threeYear: 399 },
    specs: { Warranty: "$10,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Domain doğrulaması (5–10 dk)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Tüm modern tarayıcılarla uyumluluk",
      "Ücretsiz tekrar verme",
      "30 gün para iade garantisi",
    ],
    rating: 4.4, reviewCount: 320, featured: false, inStock: true,
  },

  {
    name: "GeoTrust DV",
    slug: "geotrust-dv",
    category: "SSL",
    validation: "DV",
    productType: "Standard",
    tier: "Basic",
    brand: "GeoTrust",
    description: "GeoTrust DV, yüksek garantili ve hızlı aktivasyonlu domain doğrulamalı SSL sertifikasıdır.",
    shortDescription: "Yüksek garantili DV SSL.",
    price: { oneYear: 799, twoYear: 1499, threeYear: 2099 },
    specs: { Warranty: "$500,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Domain doğrulaması (5–10 dk)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "$500,000 garanti koruması",
      "7/24 teknik destek",
      "30 gün para iade garantisi",
    ],
    rating: 4.7, reviewCount: 175, featured: true, inStock: true,
  },

  // ─────────────────────────────────────────────
  // DV — Wildcard (Single Domain tab'ında gösterilir)
  // ─────────────────────────────────────────────

  {
    name: "Sectigo Wildcard DV",
    slug: "sectigo-wildcard-dv",
    category: "SSL",
    validation: "DV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "Sectigo",
    description: "Sectigo Wildcard DV, *.domain.com formatındaki tüm alt domainleri tek sertifikayla koruyan ekonomik çözümdür.",
    shortDescription: "Tüm alt domainler için ekonomik DV.",
    price: { oneYear: 1299, twoYear: 2399, threeYear: 3399 },
    specs: { Warranty: "$10,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Sınırsız subdomain",
      "Tek sertifika ile kolay yönetim",
      "30 gün para iade garantisi",
    ],
    rating: 4.5, reviewCount: 130, featured: false, inStock: true,
  },

  {
    name: "Thawte Wildcard SSL 123 DV",
    slug: "thawte-wildcard-ssl123-dv",
    category: "SSL",
    validation: "DV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "Thawte",
    description: "Thawte Wildcard SSL 123, tüm alt domainleri tek sertifikayla koruyan güvenilir DV wildcard çözümüdür.",
    shortDescription: "Güvenilir wildcard DV SSL.",
    price: { oneYear: 2499, twoYear: 4599, threeYear: 6499 },
    specs: { Warranty: "$100,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "$100,000 garanti koruması",
      "7/24 teknik destek",
      "30 gün para iade garantisi",
    ],
    rating: 4.6, reviewCount: 100, featured: false, inStock: true,
  },

  {
    name: "PositiveSSL Wildcard DV",
    slug: "positivessl-wildcard-dv",
    category: "SSL",
    validation: "DV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "PositiveSSL",
    description: "PositiveSSL Wildcard, tüm alt domainleri en uygun fiyatla koruyan DV wildcard sertifikasıdır.",
    shortDescription: "En uygun fiyatlı wildcard DV SSL.",
    price: { oneYear: 999, twoYear: 1849, threeYear: 2599 },
    specs: { Warranty: "$10,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Sınırsız subdomain",
      "Tek sertifika ile kolay yönetim",
      "30 gün para iade garantisi",
    ],
    rating: 4.4, reviewCount: 115, featured: false, inStock: true,
  },

  // ─────────────────────────────────────────────
  // DV — Multi-Domain (SAN)
  // ─────────────────────────────────────────────

  {
    name: "Sectigo DV Multi-Domain",
    slug: "sectigo-dv-multi-domain",
    category: "SSL",
    validation: "DV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "Sectigo",
    description: "Sectigo DV Multi-Domain, SAN desteği ile birden fazla domaini tek sertifikayla koruyan esnek DV çözümüdür.",
    shortDescription: "Çoklu domain için DV SAN SSL.",
    price: { oneYear: 799, twoYear: 1499, threeYear: 2099, pricePerDomain: 150 },
    specs: { Warranty: "$10,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain eklenebilir",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Tek sertifika ile yönetim kolaylığı",
      "30 gün para iade garantisi",
    ],
    rating: 4.5, reviewCount: 90, featured: false, inStock: true,
  },

  {
    name: "Thawte SSL 123 DV Multi-Domain",
    slug: "thawte-ssl123-dv-multi-domain",
    category: "SSL",
    validation: "DV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "Thawte",
    description: "Thawte SSL 123 Multi-Domain, birden fazla domaini tek DV sertifikasıyla koruyan güvenilir SAN çözümüdür.",
    shortDescription: "Güvenilir çoklu domain DV SSL.",
    price: { oneYear: 1499, twoYear: 2799, threeYear: 3899, pricePerDomain: 250 },
    specs: { Warranty: "$100,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain eklenebilir",
      "256-bit şifreleme",
      "$100,000 garanti koruması",
      "7/24 teknik destek",
      "30 gün para iade garantisi",
    ],
    rating: 4.6, reviewCount: 85, featured: false, inStock: true,
  },

  {
    name: "PositiveSSL Multi-Domain DV",
    slug: "positivessl-dv-multi-domain",
    category: "SSL",
    validation: "DV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "PositiveSSL",
    description: "PositiveSSL Multi-Domain, çok sayıda domaini en uygun fiyatla tek DV sertifikasında toplayan çözümdür.",
    shortDescription: "Ekonomik çoklu domain DV SSL.",
    price: { oneYear: 599, twoYear: 1099, threeYear: 1499, pricePerDomain: 120 },
    specs: { Warranty: "$10,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain eklenebilir",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Tek sertifika ile yönetim kolaylığı",
      "30 gün para iade garantisi",
    ],
    rating: 4.4, reviewCount: 110, featured: false, inStock: true,
  },

  {
    name: "GeoTrust DV Multi-Domain",
    slug: "geotrust-dv-multi-domain",
    category: "SSL",
    validation: "DV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "GeoTrust",
    description: "GeoTrust DV Multi-Domain, yüksek garanti ve SAN desteği ile birden fazla domaini koruyan DV çözümüdür.",
    shortDescription: "Yüksek garantili çoklu domain DV SSL.",
    price: { oneYear: 1999, twoYear: 3699, threeYear: 5199, pricePerDomain: 350 },
    specs: { Warranty: "$500,000", Encryption: "256-bit", Issuance: "5–10 dk" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain eklenebilir",
      "$500,000 garanti koruması",
      "256-bit şifreleme",
      "7/24 teknik destek",
      "30 gün para iade garantisi",
    ],
    rating: 4.7, reviewCount: 95, featured: true, inStock: true,
  },

]
