export const ovProducts = [

  // ─────────────────────────────────────────────
  // OV — Standard (Single Domain)
  // ─────────────────────────────────────────────

  {
    name: "DigiCert Basic OV",
    slug: "digicert-basic-ov",
    category: "SSL",
    validation: "OV",
    productType: "Standard",
    tier: "Basic",
    brand: "DigiCert",
    description: "DigiCert Basic OV, şirket kimliğini doğrulayan kurumsal güven sağlayan giriş seviyesi OV SSL sertifikasıdır.",
    shortDescription: "DigiCert giriş seviyesi OV SSL.",
    price: { oneYear: 1899, twoYear: 3499, threeYear: 4899 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1–2 gün" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "Sınırsız sertifika yeniden oluşturma",
      "Otomatik SSL yaşam döngüsü yönetimi",
      "Uzman teknik destek",
      "Merkezi SSL yönetim paneli",
    ],
    rating: 4.9, reviewCount: 110, featured: true, inStock: true,
  },

  {
    name: "DigiCert Secure Site OV",
    slug: "digicert-secure-site-ov",
    category: "SSL",
    validation: "OV",
    productType: "Standard",
    tier: "Premium",
    brand: "DigiCert",
    description: "DigiCert Secure Site OV, gelişmiş güvenlik özellikleri ve kurumsal doğrulama ile premium OV çözümüdür.",
    shortDescription: "Premium OV SSL çözümü.",
    price: { oneYear: 3499, twoYear: 6599, threeYear: 9299 },
    specs: { Warranty: "$1,500,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Şirket kimlik doğrulaması",
      "Öncelikli sertifika doğrulama ve aktivasyon",
      "Web sitesi güven mührü (Trust Seal)",
      "Alan adı itibar izleme",
      "Web sitesi güvenlik açığı taraması",
      "Gelişmiş SSL yönetim paneli",
    ],
    rating: 4.9, reviewCount: 140, featured: true, inStock: true,
  },

  {
    name: "DigiCert Secure Site Pro OV",
    slug: "digicert-secure-site-pro-ov",
    category: "SSL",
    validation: "OV",
    productType: "Standard",
    tier: "Enterprise",
    brand: "DigiCert",
    description: "DigiCert Secure Site Pro OV, en üst düzey kurumsal doğrulama ve gelişmiş güvenlik özellikleri sunan premium OV SSL'dir.",
    shortDescription: "En üst seviye OV SSL.",
    price: { oneYear: 4999, twoYear: 9399, threeYear: 13299 },
    specs: { Warranty: "$1,750,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Gelişmiş SSL sertifika yaşam döngüsü otomasyonu",
      "Öncelikli doğrulama ve aktivasyon",
      "Web sitesi güven mührü (Trust Seal)",
      "Alan adı itibar izleme",
      "Web sitesi güvenlik açığı taraması",
      "Certificate Transparency (CT) log izleme",
    ],
    rating: 4.9, reviewCount: 160, featured: true, inStock: true,
  },

  {
    name: "Sectigo OV",
    slug: "sectigo-ov",
    category: "SSL",
    validation: "OV",
    productType: "Standard",
    tier: "Basic",
    brand: "Sectigo",
    description: "Sectigo OV, kurumsal web siteleri için şirket kimlik doğrulamalı güvenilir OV SSL sertifikasıdır.",
    shortDescription: "Kurumsal güven için OV SSL.",
    price: { oneYear: 999, twoYear: 1899, threeYear: 2699 },
    specs: { Warranty: "$1,000,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "7/24 uzman teknik destek",
      "Sınırsız sunucu lisansı",
      "Web sitesi güven mührü",
      "30 gün para iade garantisi",
    ],
    rating: 4.6, reviewCount: 75, featured: false, inStock: true,
  },

  {
    name: "PositiveSSL OV",
    slug: "positivessl-ov",
    category: "SSL",
    validation: "OV",
    productType: "Standard",
    tier: "Basic",
    brand: "PositiveSSL",
    description: "PositiveSSL OV, ekonomik fiyatıyla şirket kimlik doğrulaması sunan OV SSL sertifikasıdır.",
    shortDescription: "Ekonomik OV SSL çözümü.",
    price: { oneYear: 799, twoYear: 1499, threeYear: 2099 },
    specs: { Warranty: "$250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "HTTPS güven kilidi",
      "Tüm modern tarayıcılarla uyumluluk",
      "Ücretsiz tekrar verme",
      "30 gün para iade garantisi",
    ],
    rating: 4.5, reviewCount: 65, featured: false, inStock: true,
  },

  {
    name: "GeoTrust TrueBusinessID OV",
    slug: "geotrust-truebusinessid-ov",
    category: "SSL",
    validation: "OV",
    productType: "Standard",
    tier: "Basic",
    brand: "GeoTrust",
    description: "GeoTrust TrueBusinessID OV, yüksek garantili ve güvenilir şirket doğrulamalı OV SSL sertifikasıdır.",
    shortDescription: "Yüksek garantili OV SSL.",
    price: { oneYear: 1499, twoYear: 2699, threeYear: 3699 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: false },
    features: [
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "$1,250,000 garanti koruması",
      "7/24 teknik destek",
      "Web sitesi güven mührü",
      "30 gün para iade garantisi",
    ],
    rating: 4.8, reviewCount: 90, featured: true, inStock: true,
  },

  // ─────────────────────────────────────────────
  // OV — Wildcard (Single Domain tab'ında gösterilir)
  // ─────────────────────────────────────────────

  {
    name: "DigiCert Wildcard Basic OV",
    slug: "digicert-basic-wildcard-ov",
    category: "SSL",
    validation: "OV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "DigiCert",
    description: "DigiCert Wildcard Basic OV, tüm alt domainleri şirket doğrulamasıyla koruyan kurumsal wildcard OV SSL'dir.",
    shortDescription: "DigiCert wildcard OV giriş seviyesi.",
    price: { oneYear: 4999, twoYear: 9399, threeYear: 13299 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "Otomatik SSL yaşam döngüsü yönetimi",
      "Uzman teknik destek",
      "Merkezi SSL yönetim paneli",
    ],
    rating: 4.9, reviewCount: 120, featured: true, inStock: true,
  },

  {
    name: "DigiCert Wildcard Secure Site OV",
    slug: "digicert-secure-site-wildcard-ov",
    category: "SSL",
    validation: "OV",
    productType: "Wildcard",
    tier: "Premium",
    brand: "DigiCert",
    description: "DigiCert Secure Site Wildcard OV, gelişmiş kurumsal güvenlik ve wildcard desteği sunan premium OV sertifikasıdır.",
    shortDescription: "Premium wildcard OV SSL.",
    price: { oneYear: 6999, twoYear: 12999, threeYear: 18299 },
    specs: { Warranty: "$1,500,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "Şirket kimlik doğrulaması",
      "Web sitesi güven mührü (Trust Seal)",
      "Alan adı itibar izleme",
      "Güvenlik açığı taraması",
      "Gelişmiş SSL yönetim paneli",
    ],
    rating: 4.9, reviewCount: 150, featured: true, inStock: true,
  },

  {
    name: "DigiCert Wildcard Secure Site Pro OV",
    slug: "digicert-secure-site-pro-wildcard-ov",
    category: "SSL",
    validation: "OV",
    productType: "Wildcard",
    tier: "Enterprise",
    brand: "DigiCert",
    description: "DigiCert Secure Site Pro Wildcard OV, en üst düzey kurumsal wildcard OV sertifikasıdır.",
    shortDescription: "En üst seviye wildcard OV SSL.",
    price: { oneYear: 8999, twoYear: 16999, threeYear: 23999 },
    specs: { Warranty: "$1,750,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "Gelişmiş SSL yaşam döngüsü otomasyonu",
      "Öncelikli doğrulama ve aktivasyon",
      "Web sitesi güven mührü (Trust Seal)",
      "CT log izleme",
      "Certificate Transparency desteği",
    ],
    rating: 5.0, reviewCount: 170, featured: true, inStock: true,
  },

  {
    name: "Sectigo Wildcard OV",
    slug: "sectigo-wildcard-ov",
    category: "SSL",
    validation: "OV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "Sectigo",
    description: "Sectigo Wildcard OV, tüm alt domainleri şirket doğrulamasıyla koruyan kurumsal wildcard sertifikasıdır.",
    shortDescription: "Kurumsal wildcard OV SSL.",
    price: { oneYear: 2999, twoYear: 5599, threeYear: 7799 },
    specs: { Warranty: "$1,000,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "Şirket kimlik doğrulaması",
      "7/24 uzman teknik destek",
      "Sınırsız sunucu lisansı",
      "Web sitesi güven mührü",
      "30 gün para iade garantisi",
    ],
    rating: 4.7, reviewCount: 92, featured: false, inStock: true,
  },

  {
    name: "Thawte Wildcard SSL Webserver OV",
    slug: "thawte-webserver-wildcard-ov",
    category: "SSL",
    validation: "OV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "Thawte",
    description: "Thawte Wildcard SSL Webserver OV, şirket doğrulamasıyla tüm alt domainleri koruyan wildcard OV sertifikasıdır.",
    shortDescription: "Güvenilir wildcard OV SSL.",
    price: { oneYear: 3499, twoYear: 6599, threeYear: 9199 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "Şirket kimlik doğrulaması",
      "$1,250,000 garanti koruması",
      "7/24 teknik destek",
      "Tüm modern tarayıcılarla uyumluluk",
      "30 gün para iade garantisi",
    ],
    rating: 4.7, reviewCount: 88, featured: false, inStock: true,
  },

  {
    name: "PositiveSSL Wildcard OV",
    slug: "positivessl-wildcard-ov",
    category: "SSL",
    validation: "OV",
    productType: "Wildcard",
    tier: "Basic",
    brand: "PositiveSSL",
    description: "PositiveSSL Wildcard OV, ekonomik fiyatıyla alt domainleri şirket doğrulamalı koruma altına alan wildcard sertifikasıdır.",
    shortDescription: "Ekonomik wildcard OV SSL.",
    price: { oneYear: 1999, twoYear: 3699, threeYear: 5199 },
    specs: { Warranty: "$250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: false, wildcard: true },
    features: [
      "Tüm alt domainleri kapsar (*.domain.com)",
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "Sınırsız sunucu lisansı",
      "Ücretsiz tekrar verme",
      "30 gün para iade garantisi",
    ],
    rating: 4.5, reviewCount: 58, featured: false, inStock: true,
  },

  // ─────────────────────────────────────────────
  // OV — Multi-Domain (SAN)
  // ─────────────────────────────────────────────

  {
    name: "DigiCert Basic OV Multi-Domain",
    slug: "digicert-basic-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "DigiCert",
    description: "DigiCert Basic OV Multi-Domain, SAN desteği ile birden fazla domaini tek kurumsal sertifikayla koruyan OV çözümüdür.",
    shortDescription: "DigiCert çoklu domain OV SSL.",
    price: { oneYear: 2999, twoYear: 5599, threeYear: 7799, pricePerDomain: 400 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1–2 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "Şirket kimlik doğrulaması",
      "Otomatik SSL yaşam döngüsü yönetimi",
      "Uzman teknik destek",
      "Merkezi SSL yönetim paneli",
    ],
    rating: 4.9, reviewCount: 85, featured: true, inStock: true,
  },

  {
    name: "DigiCert Secure Site OV Multi-Domain",
    slug: "digicert-secure-site-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Premium",
    brand: "DigiCert",
    description: "DigiCert Secure Site OV Multi-Domain, gelişmiş güvenlik ve SAN desteği ile kurumsal çoklu domain OV çözümüdür.",
    shortDescription: "Premium çoklu domain OV SSL.",
    price: { oneYear: 4999, twoYear: 9399, threeYear: 13299, pricePerDomain: 600 },
    specs: { Warranty: "$1,500,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "Öncelikli sertifika doğrulama",
      "Web sitesi güven mührü (Trust Seal)",
      "Alan adı itibar izleme",
      "Güvenlik açığı taraması",
    ],
    rating: 4.9, reviewCount: 110, featured: true, inStock: true,
  },

  {
    name: "DigiCert Secure Site Pro OV Multi-Domain",
    slug: "digicert-secure-site-pro-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Enterprise",
    brand: "DigiCert",
    description: "DigiCert Secure Site Pro OV Multi-Domain, en üst düzey kurumsal çoklu domain OV SSL çözümüdür.",
    shortDescription: "Enterprise çoklu domain OV SSL.",
    price: { oneYear: 6999, twoYear: 12999, threeYear: 18299, pricePerDomain: 800 },
    specs: { Warranty: "$1,750,000", Encryption: "256-bit", Issuance: "1 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "Gelişmiş SSL yaşam döngüsü otomasyonu",
      "CT log izleme",
      "Web sitesi güven mührü (Trust Seal)",
      "Certificate Transparency desteği",
    ],
    rating: 5.0, reviewCount: 130, featured: true, inStock: true,
  },

  {
    name: "Sectigo OV Multi-Domain",
    slug: "sectigo-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "Sectigo",
    description: "Sectigo OV Multi-Domain, SAN desteği ile birden fazla domaini kurumsal doğrulama ile koruyan OV çözümüdür.",
    shortDescription: "Kurumsal çoklu domain OV SSL.",
    price: { oneYear: 2499, twoYear: 4599, threeYear: 6399, pricePerDomain: 300 },
    specs: { Warranty: "$1,000,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "Şirket kimlik doğrulaması",
      "7/24 uzman teknik destek",
      "Web sitesi güven mührü",
      "30 gün para iade garantisi",
    ],
    rating: 4.7, reviewCount: 95, featured: true, inStock: true,
  },

  {
    name: "Thawte SSL Webserver OV Multi-Domain",
    slug: "thawte-ssl-webserver-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "Thawte",
    description: "Thawte SSL Webserver OV Multi-Domain, birden fazla domaini şirket doğrulamasıyla koruyan SAN çözümüdür.",
    shortDescription: "Güvenilir çoklu domain OV SSL.",
    price: { oneYear: 2999, twoYear: 5599, threeYear: 7799, pricePerDomain: 350 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "$1,250,000 garanti koruması",
      "7/24 teknik destek",
      "Tüm modern tarayıcılarla uyumluluk",
      "30 gün para iade garantisi",
    ],
    rating: 4.7, reviewCount: 80, featured: false, inStock: true,
  },

  {
    name: "PositiveSSL OV Multi-Domain",
    slug: "positivessl-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "PositiveSSL",
    description: "PositiveSSL OV Multi-Domain, ekonomik fiyatıyla birden fazla domaini kurumsal doğrulama ile koruyan SAN çözümüdür.",
    shortDescription: "Ekonomik çoklu domain OV SSL.",
    price: { oneYear: 1499, twoYear: 2799, threeYear: 3899, pricePerDomain: 220 },
    specs: { Warranty: "$250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "Şirket kimlik doğrulaması",
      "256-bit şifreleme",
      "Ücretsiz tekrar verme",
      "30 gün para iade garantisi",
    ],
    rating: 4.5, reviewCount: 70, featured: false, inStock: true,
  },

  {
    name: "GeoTrust TrueBusinessID OV Multi-Domain",
    slug: "geotrust-truebusinessid-ov-multi-domain",
    category: "SSL",
    validation: "OV",
    productType: "Multi-Domain",
    tier: "Basic",
    brand: "GeoTrust",
    description: "GeoTrust TrueBusinessID OV Multi-Domain, yüksek garanti ve SAN desteği ile kurumsal çoklu domain OV çözümüdür.",
    shortDescription: "Yüksek garantili çoklu domain OV SSL.",
    price: { oneYear: 2999, twoYear: 5599, threeYear: 7799, pricePerDomain: 450 },
    specs: { Warranty: "$1,250,000", Encryption: "256-bit", Issuance: "1–3 gün" },
    domainSupport: { standard: true, wildcard: true, multiDomainLimit: 3 },
    features: [
      "3 domain dahil (SAN)",
      "Ek domain ve wildcard eklenebilir",
      "$1,250,000 garanti koruması",
      "7/24 teknik destek",
      "Web sitesi güven mührü",
      "30 gün para iade garantisi",
    ],
    rating: 4.8, reviewCount: 88, featured: false, inStock: true,
  },

]
